version: '3'
services:
  
  hawk:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/hawk
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes: 
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"


volumes:
  db-data:
