THREAD_LIMIT:10
REDASH_KEY:Key EsMfKqjqBZ7LGJzaHjopO28TdtpuzrOs63DGAjYI

EMAIL_FROM:hawkbot.bukalapak@gmail.com
SMTP_ADDRESS:smtp.gmail.com
SMTP_PORT:587
SMTP_DOMAIN:gmail.com
SMTP_PASSWORD:Bukanbot2018
