# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

production:
  adapter: mysql2
  username: <%= ENV['MYSQL_USERNAME_PROD'] %>
  password: <%= ENV['MYSQL_PASSWORD_PROD'] %>
  host: <%= ENV['MYSQL_HOST_PROD'] %>
  port: <%= ENV['MYSQL_PORT_PROD'] %>
  database: <%= ENV['MYSQL_DBNAME_PROD'] %>
