apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    release: '{{.variable.VERSION}}'
  name: {{.config.projectName}}-{{.service.name}}-{{.environment.name}}
  labels:
    project: "{{.config.projectName}}"
    service: "{{.service.name}}"
    env: "{{.environment.name}}"
  namespace: {{.variable.VAR_KUBE_NAMESPACE}}
spec:
  selector:
    matchLabels:
      project: {{.config.projectName}}
      service: {{.service.name}}
      env: {{.environment.name}}
  replicas: {{.environment.replica}}
  revisionHistoryLimit: 3
  template:
    metadata:
      annotations:
        release: '{{.variable.VERSION}}'
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{.service.port}}"
      labels:
        project: {{.config.projectName}}
        service: {{.service.name}}
        env: {{.environment.name}}
    spec:
      nodeSelector:
        env: {{.environment.name}}
      imagePullSecrets:
      - name: blregistry
      containers:
      - name: {{.config.projectName}}-{{.service.name}}
        image: {{.variable.CI_REGISTRY}}/bukalapak/{{.config.projectName}}/{{.service.name}}:{{.variable.VERSION}}
        livenessProbe:
          httpGet:
            path: /{{.service.healthz}}
            port: {{.service.port}}
          initialDelaySeconds: {{.service.delay}}
          timeoutSeconds: {{.service.timeout}}
        readinessProbe:
          httpGet:
            path: /{{.service.healthz}}
            port: {{.service.port}}
          initialDelaySeconds: {{.service.delay}}
          timeoutSeconds: {{.service.timeout}}
        ports:
        - containerPort: {{.service.port}}
        resources:
          limits:
            memory: {{.service.maxMem}}Gi
            cpu: {{.service.maxCpu}}
          requests:
            memory: {{.service.minMem}}Gi
            cpu: {{.service.minCpu}}
        command:
        - envconsul
        args:
        - -consul=$(CONSUL_SERVER)
        - -sanitize
        - -upcase
        - -prefix={{.variable.VAR_CONSUL_PREFIX}}
        - rails
        - s
        - -e
        - production
        env:
        - name: CONSUL_SERVER
          valueFrom:
            configMapKeyRef:
              name: consul-config
              key: client
      - name: redis-hawk-cache
        image: redis:4
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
        command:
        - redis-server
        resources:
          limits:
            memory: 0.5Gi
            cpu: 1
          requests:
            memory: 0.2Gi
            cpu: 500m
